/**
 * City -> country lookup.
 *
 * CVs routinely name only a city ("Residency at Villa Medici, Rome"), but a
 * catalogue that filters by country needs the country. Inferring it from a
 * known list is safe in a way that guessing a venue or a year is not: the
 * mapping is a fact about the world, not about the artist.
 *
 * Anything not listed is left undefined rather than guessed, and every
 * inferred country is flagged on the record so a reviewer can see that the
 * source line did not say it.
 */
export const CITY_COUNTRY: Record<string, string> = {
  amsterdam: "Netherlands",
  antwerp: "Belgium",
  athens: "Greece",
  barcelona: "Spain",
  basel: "Switzerland",
  beijing: "China",
  beirut: "Lebanon",
  belgrade: "Serbia",
  bergen: "Norway",
  berlin: "Germany",
  bilbao: "Spain",
  bologna: "Italy",
  bolzano: "Italy",
  bratislava: "Slovakia",
  bristol: "United Kingdom",
  brussels: "Belgium",
  bucharest: "Romania",
  budapest: "Hungary",
  "buenos aires": "Argentina",
  cairo: "Egypt",
  "cape town": "South Africa",
  chicago: "United States",
  cologne: "Germany",
  copenhagen: "Denmark",
  dakar: "Senegal",
  dresden: "Germany",
  dubai: "United Arab Emirates",
  dublin: "Ireland",
  dusseldorf: "Germany",
  düsseldorf: "Germany",
  edinburgh: "United Kingdom",
  florence: "Italy",
  frankfurt: "Germany",
  geneva: "Switzerland",
  genoa: "Italy",
  ghent: "Belgium",
  glasgow: "United Kingdom",
  gothenburg: "Sweden",
  hamburg: "Germany",
  helsinki: "Finland",
  "hong kong": "China",
  hydra: "Greece",
  istanbul: "Türkiye",
  johannesburg: "South Africa",
  kyiv: "Ukraine",
  "la paz": "Bolivia",
  leipzig: "Germany",
  lisbon: "Portugal",
  ljubljana: "Slovenia",
  london: "United Kingdom",
  "los angeles": "United States",
  luxembourg: "Luxembourg",
  lyon: "France",
  madrid: "Spain",
  malaga: "Spain",
  málaga: "Spain",
  marseille: "France",
  "mexico city": "Mexico",
  milan: "Italy",
  montreal: "Canada",
  moscow: "Russia",
  munich: "Germany",
  naples: "Italy",
  "new york": "United States",
  nicosia: "Cyprus",
  oslo: "Norway",
  palermo: "Italy",
  paris: "France",
  porto: "Portugal",
  prague: "Czech Republic",
  reykjavik: "Iceland",
  riga: "Latvia",
  rome: "Italy",
  rotterdam: "Netherlands",
  "san francisco": "United States",
  "sao paulo": "Brazil",
  "são paulo": "Brazil",
  seoul: "South Korea",
  shanghai: "China",
  singapore: "Singapore",
  sofia: "Bulgaria",
  stockholm: "Sweden",
  strasbourg: "France",
  stuttgart: "Germany",
  sydney: "Australia",
  tallinn: "Estonia",
  tbilisi: "Georgia",
  "tel aviv": "Israel",
  thessaloniki: "Greece",
  tokyo: "Japan",
  toronto: "Canada",
  turin: "Italy",
  utrecht: "Netherlands",
  valencia: "Spain",
  venice: "Italy",
  vienna: "Austria",
  vilnius: "Lithuania",
  warsaw: "Poland",
  yerevan: "Armenia",
  zagreb: "Croatia",
  zurich: "Switzerland",
  zürich: "Switzerland",
};

export function countryForCity(city: string | undefined): string | undefined {
  if (!city) return undefined;
  return CITY_COUNTRY[city.trim().toLowerCase()];
}

export function isKnownCity(value: string | undefined): boolean {
  return countryForCity(value) !== undefined;
}
